### ISSUE TITLE
Add support for component tests

### ISSUE THREAD

**Issue by petrkrejcik** [bahmutov/cypress-toy-visual-testing#29]
I suppose the plugin is not expected to work with component tests. I assume that because the README doesn't explicitly say that and moreover the plugin doesn't work for component tests. It throws an error:
```
Cannot find module 'path'
```

Would it be difficult to make the plugin work for component tests?

Cypress version: 13.11
Node: 18

**Comment by bahmutov** [comment]
Can you provide more information about the error? The framework / bundler / the plugin version? I am using this plugin for visually testing components in the course https://cypress.tips/courses/visual-testing

**Comment by petrkrejcik** [comment]
| Header | Header |
|--------|--------|
| Cypress | 13.11.0 |
| Browser | Electron 118 (headless) |
| Node Version | v18.18.0 | 
| Framework | React 17 |
| Bundler | Webpack 5.72.1 |
| Transpiler | `swc-loader` |
| @bahmutov/cypress-toy-visual-testing | 1.6.2 |

![image](https://github.com/bahmutov/cypress-toy-visual-testing/assets/5626914/6f62a6ca-dd22-4cc6-bb90-c8f7a71d64ae)

**Comment by bahmutov** [comment]
Yeah, webpack 5 does not have a polyfill for this https://github.com/bahmutov/cypress-toy-visual-testing/blob/8103ca8c2eb92629edba5239053d148702c30db4/src/support/commands.ts#L1 Let me see if I can remove it
